export const RAW_ROWS = [
  {
    row: 2,
    date: "2025-04-01",
    category: "Marketing",
    description: "Meta Ads — April Week 1",
    amount: 12500,
    notes: "ROAS 2.4x, 42 orders attributed",
    channel: "Meta",
  },
  {
    row: 3,
    date: "2025-04-05",
    category: "COGS",
    description: "Packaging material restock — 500 units",
    amount: 3400,
    notes: "Box + bubble wrap batch",
    channel: "Operations",
  },
  {
    row: 4,
    date: "2025-04-08",
    category: "Marketing",
    description: "Google Shopping Ads — Week 1",
    amount: 8200,
    notes: "ROAS 1.9x, 18 orders",
    channel: "Google",
  },
  {
    row: 5,
    date: "2025-04-10",
    category: "Returns",
    description: "Return processing — 6 units",
    amount: 1800,
    notes: "Mostly RTO from DTDC zone",
    channel: "Shiprocket",
  },
  {
    row: 6,
    date: "2025-04-14",
    category: "Marketing",
    description: "Instagram influencer @techreviewer",
    amount: 5000,
    notes: "Promo code TECH10, 12 conversions",
    channel: "Instagram",
  },
  {
    row: 7,
    date: "2025-04-15",
    category: "Operations",
    description: "Warehouse storage — April",
    amount: 4200,
    notes: "Fulfillment center monthly fee",
    channel: "Operations",
  },
  {
    row: 8,
    date: "2025-04-20",
    category: "Marketing",
    description: "Meta Ads — April Week 3",
    amount: 11000,
    notes: "ROAS 2.1x, 38 orders attributed",
    channel: "Meta",
  },
  {
    row: 9,
    date: "2025-04-22",
    category: "Returns",
    description: "Return processing — 4 units damaged",
    amount: 1200,
    notes: "Damaged in transit, courier claim filed",
    channel: "Shiprocket",
  },
  {
    row: 10,
    date: "2025-04-25",
    category: "COGS",
    description: "Product procurement — 200 units batch",
    amount: 38000,
    notes: "Batch #Q2-001 from supplier",
    channel: "Procurement",
  },
  {
    row: 11,
    date: "2025-04-28",
    category: "Marketing",
    description: "Google Shopping Ads — Week 4",
    amount: 7500,
    notes: "ROAS 2.2x, 22 orders",
    channel: "Google",
  },
  {
    row: 12,
    date: "2025-05-01",
    category: "Marketing",
    description: "Meta Ads — May Week 1",
    amount: 14000,
    notes: "ROAS 2.7x, 58 orders attributed",
    channel: "Meta",
  },
  {
    row: 13,
    date: "2025-05-05",
    category: "Marketing",
    description: "Google Ads Brand — May",
    amount: 3500,
    notes: "ROAS 3.1x, 14 brand searches converted",
    channel: "Google",
  },
  {
    row: 14,
    date: "2025-05-06",
    category: "Returns",
    description: "Return processing — 3 units",
    amount: 900,
    notes: "Size/fit issue, full refund",
    channel: "Shiprocket",
  },
  {
    row: 15,
    date: "2025-05-08",
    category: "Operations",
    description: "Warehouse storage — May partial",
    amount: 1400,
    notes: "Prorated for first 10 days",
    channel: "Operations",
  },
];
