export const RAW_ORDERS = [
  {
    id: "SHPFY-1001",
    name: "#1001",
    created_at: "2025-04-01T10:00:00Z",
    financial_status: "paid",
    fulfillment_status: "fulfilled",
    total_price: "1850.00",
    subtotal_price: "1770.00",
    total_shipping_price: "80.00",
    total_discounts: "0.00",
    currency: "INR",
    customer: {
      first_name: "Arjun",
      last_name: "Mehta",
      email: "arjun@example.com",
    },
    shipping_address: { city: "Mumbai", province_code: "MH", zip: "400001" },
    line_items: [
      {
        title: "Wireless Earbuds Pro",
        quantity: 1,
        price: "1850.00",
        sku: "WEP-001",
      },
    ],
    tags: [],
  },
  {
    id: "SHPFY-1002",
    name: "#1002",
    created_at: "2025-04-03T11:30:00Z",
    financial_status: "paid",
    fulfillment_status: "unfulfilled",
    total_price: "3200.00",
    subtotal_price: "3120.00",
    total_shipping_price: "80.00",
    total_discounts: "0.00",
    currency: "INR",
    customer: {
      first_name: "Priya",
      last_name: "Sharma",
      email: "priya@example.com",
    },
    shipping_address: { city: "Delhi", province_code: "DL", zip: "110001" },
    line_items: [
      { title: "Laptop Stand", quantity: 2, price: "1600.00", sku: "LS-002" },
    ],
    tags: [],
  },
  {
    id: "SHPFY-1003",
    name: "#1003",
    created_at: "2025-04-05T09:15:00Z",
    financial_status: "paid",
    fulfillment_status: "fulfilled",
    total_price: "750.00",
    subtotal_price: "690.00",
    total_shipping_price: "60.00",
    total_discounts: "0.00",
    currency: "INR",
    customer: {
      first_name: "Rahul",
      last_name: "Verma",
      email: "rahul@example.com",
    },
    shipping_address: { city: "Bangalore", province_code: "KA", zip: "560001" },
    line_items: [
      {
        title: "Phone Case Premium",
        quantity: 3,
        price: "250.00",
        sku: "PC-003",
      },
    ],
    tags: [],
  },
  {
    id: "SHPFY-1004",
    name: "#1004",
    created_at: "2025-04-07T14:00:00Z",
    financial_status: "paid",
    fulfillment_status: "fulfilled",
    total_price: "5500.00",
    subtotal_price: "5420.00",
    total_shipping_price: "80.00",
    total_discounts: "0.00",
    currency: "INR",
    customer: {
      first_name: "Neha",
      last_name: "Gupta",
      email: "neha@example.com",
    },
    shipping_address: { city: "Chennai", province_code: "TN", zip: "600001" },
    line_items: [
      {
        title: "Mechanical Keyboard TKL",
        quantity: 1,
        price: "5500.00",
        sku: "MK-004",
      },
    ],
    tags: ["high-value"],
  },
  {
    id: "SHPFY-1005",
    name: "#1005",
    created_at: "2025-04-09T16:45:00Z",
    financial_status: "refunded",
    fulfillment_status: "cancelled",
    total_price: "980.00",
    subtotal_price: "920.00",
    total_shipping_price: "60.00",
    total_discounts: "0.00",
    currency: "INR",
    customer: {
      first_name: "Vikram",
      last_name: "Singh",
      email: "vikram@example.com",
    },
    shipping_address: { city: "Hyderabad", province_code: "TG", zip: "500001" },
    line_items: [
      {
        title: "USB-C Hub 7-in-1",
        quantity: 1,
        price: "980.00",
        sku: "UH-005",
      },
    ],
    tags: ["cancelled"],
  },
  {
    id: "SHPFY-1006",
    name: "#1006",
    created_at: "2025-04-12T08:20:00Z",
    financial_status: "paid",
    fulfillment_status: "fulfilled",
    total_price: "2100.00",
    subtotal_price: "2020.00",
    total_shipping_price: "80.00",
    total_discounts: "0.00",
    currency: "INR",
    customer: {
      first_name: "Kavya",
      last_name: "Nair",
      email: "kavya@example.com",
    },
    shipping_address: { city: "Pune", province_code: "MH", zip: "411001" },
    line_items: [
      {
        title: "LED Desk Lamp Smart",
        quantity: 1,
        price: "2100.00",
        sku: "DL-006",
      },
    ],
    tags: [],
  },
  {
    id: "SHPFY-1007",
    name: "#1007",
    created_at: "2025-04-15T12:00:00Z",
    financial_status: "paid",
    fulfillment_status: "fulfilled",
    total_price: "450.00",
    subtotal_price: "390.00",
    total_shipping_price: "60.00",
    total_discounts: "0.00",
    currency: "INR",
    customer: {
      first_name: "Suresh",
      last_name: "Patel",
      email: "suresh@example.com",
    },
    shipping_address: { city: "Kolkata", province_code: "WB", zip: "700001" },
    line_items: [
      {
        title: "Cable Management Kit",
        quantity: 3,
        price: "150.00",
        sku: "CM-007",
      },
    ],
    tags: [],
  },
  {
    id: "SHPFY-1008",
    name: "#1008",
    created_at: "2025-04-18T10:30:00Z",
    financial_status: "paid",
    fulfillment_status: "unfulfilled",
    total_price: "7800.00",
    subtotal_price: "7720.00",
    total_shipping_price: "80.00",
    total_discounts: "0.00",
    currency: "INR",
    customer: {
      first_name: "Anita",
      last_name: "Rao",
      email: "anita@example.com",
    },
    shipping_address: { city: "Ahmedabad", province_code: "GJ", zip: "380001" },
    line_items: [
      {
        title: "Monitor Arm Dual",
        quantity: 2,
        price: "3900.00",
        sku: "MA-008",
      },
    ],
    tags: ["high-value"],
  },
  {
    id: "SHPFY-1009",
    name: "#1009",
    created_at: "2025-04-22T15:00:00Z",
    financial_status: "paid",
    fulfillment_status: "fulfilled",
    total_price: "1200.00",
    subtotal_price: "1140.00",
    total_shipping_price: "60.00",
    total_discounts: "0.00",
    currency: "INR",
    customer: {
      first_name: "Rohit",
      last_name: "Kumar",
      email: "rohit@example.com",
    },
    shipping_address: { city: "Jaipur", province_code: "RJ", zip: "302001" },
    line_items: [
      {
        title: "Webcam HD 1080p",
        quantity: 1,
        price: "1200.00",
        sku: "WC-009",
      },
    ],
    tags: [],
  },
  {
    id: "SHPFY-1010",
    name: "#1010",
    created_at: "2025-05-01T09:00:00Z",
    financial_status: "paid",
    fulfillment_status: "fulfilled",
    total_price: "3500.00",
    subtotal_price: "3420.00",
    total_shipping_price: "80.00",
    total_discounts: "0.00",
    currency: "INR",
    customer: {
      first_name: "Meera",
      last_name: "Krishnan",
      email: "meera@example.com",
    },
    shipping_address: { city: "Kochi", province_code: "KL", zip: "682001" },
    line_items: [
      {
        title: "Ergonomic Mouse Wireless",
        quantity: 1,
        price: "3500.00",
        sku: "EM-010",
      },
    ],
    tags: ["repeat-customer"],
  },
];

export const RAW_PRODUCTS = [
  {
    id: "PROD-001",
    title: "Wireless Earbuds Pro",
    status: "active",
    total_inventory: 45,
    variants: [
      {
        sku: "WEP-001",
        price: "1850.00",
        inventory_quantity: 45,
        title: "Default",
      },
    ],
  },
  {
    id: "PROD-002",
    title: "Laptop Stand",
    status: "active",
    total_inventory: 23,
    variants: [
      {
        sku: "LS-002",
        price: "1600.00",
        inventory_quantity: 23,
        title: "Default",
      },
    ],
  },
  {
    id: "PROD-003",
    title: "Phone Case Premium",
    status: "active",
    total_inventory: 8,
    variants: [
      {
        sku: "PC-003",
        price: "250.00",
        inventory_quantity: 8,
        title: "Default",
      },
    ],
  },
  {
    id: "PROD-004",
    title: "Mechanical Keyboard TKL",
    status: "active",
    total_inventory: 12,
    variants: [
      {
        sku: "MK-004",
        price: "5500.00",
        inventory_quantity: 12,
        title: "Default",
      },
    ],
  },
  {
    id: "PROD-005",
    title: "USB-C Hub 7-in-1",
    status: "active",
    total_inventory: 31,
    variants: [
      {
        sku: "UH-005",
        price: "980.00",
        inventory_quantity: 31,
        title: "Default",
      },
    ],
  },
  {
    id: "PROD-006",
    title: "LED Desk Lamp Smart",
    status: "active",
    total_inventory: 3,
    variants: [
      {
        sku: "DL-006",
        price: "2100.00",
        inventory_quantity: 3,
        title: "Default",
      },
    ],
  },
];
